### PR TITLE
Add Food field to check-in page

### PR DESCRIPTION
**Pull request by kitsuta**
Emergency fix for on-site Magstock registration - they need to see if someone is getting food while checking that person in.

### CODE REVIEW

**Comment by kitsuta** [comment]
Dom/Jill want this ASAP, so merging immediately.

**Comment by EliAndrewC** [comment]
+1 looks good!

**Comment by kitsuta** [comment]
Oops, didn't manage to actually fix the pep8 complaints.

**Comment by binary1230** [comment]
+1 thanks for the hustle

**Pull request merged**
