### PR TITLE
Add vehicle warning text to pre-reg page

### PR DESCRIPTION
**Pull request by kitsuta**
Adds the text as described in #15.

### CODE REVIEW

**Comment by kitsuta** [comment]
Fixes #24.

**Comment by kitsuta** [comment]
OK, now that I've previewed it on my local system, I am happy with it.

**Comment by binary1230** [comment]
+1, though there seems to be a chance of this policy changing before reg opens, which means another text change here.  from a tech standpoint looks good

**Comment by EliAndrewC** [comment]
+1 belatedly from me.

(I'm going to try to get caught up on all of the PRs that passed by while I was too busy to participate.)

**Pull request merged**
