### PR TITLE
Add functions to updated band agreement

### PR DESCRIPTION
**Pull request by cybersenshi**
Added python hooks for time and performers.
Corrected spelling of "complimentary".

### CODE REVIEW

**Comment by kitsuta** [comment]
This is merge-conflicted because GitHub decided that the previous PR merge commit is a different commit than https://github.com/magfest/magstock/pull/54/commits/a08adb8703b36324c1ef950ceb1e2ab4a8da32a0, even though it normally behaves much better than that.

+1, so if someone decides to fix the merge conflict before me, go ahead and merge.

**Comment by binary1230** [comment]
will fixup the merge conflict if it's easy (should be)

**Comment by binary1230** [comment]
for future reference: here's why there was a merge conflict:

To us humans, it appears we're asking git to change two lines in this file we added to the history.

To git, we've asked it do figure out something more complex:

in master, you had previously merged a pull request which tells git to add a new file called agreement.html (which is totally correct, because it didn't exist before)

in this pull request, you are starting from a point in the history where agreement.html doesn't already exist, and here you are asking git to add a new file called agreement.html.

So git is getting confused because: In this pull request, we're saying "hey add agreement.html with this text" and git is confused like "wait... a file named agreement.html already exists and you're asking me to create a new filed ALSO named agreement.html"

it still handles the merge mostly OK, it just needs a human to look over the merge what it thinks are two unrelated pages (rather than what's really trying to be done here which is a small 2-line change)

----

anyway, this is a pretty rare case thankfully we won't run into it much if ever.

I did the merge and am going to open a new PR which has the same result.  Chaney, please +1 that and it'll be ready to merge.

**Comment by binary1230** [comment]
replaced this PR with https://github.com/magfest/magstock/pull/55

**Pull request closed without merging**
