### PR TITLE
Create closed.html

### PR DESCRIPTION
**Pull request by binary1230**
fix prereg closed text

### CODE REVIEW

**Comment by binary1230** [comment]
@EliAndrewC @kitsuta emergency text fix, going to commit this and test on staging, please review and we'll make changes asap.

**Comment by EliAndrewC** [comment]
Looks good.

BTW, we need to start having production pull from a separate "production" branch so that we don't find ourselves in this position of "I'm gonna merge into master even though I'm not supposed to" all the time.  In cases like this we could merge into the ``production`` branch without review and then follow the normal code review options for master.

I doubt any of the Anthrocon folks care that much about the ``magstock`` repo, but given that there's been a lot of contention lately over this sort of things, we should take extra care to follow these procedures.  Unless people explicitly tell us "we don't care about that repo, do whatever you want" in which case I'm less concerned.

**Comment by binary1230** [comment]
i agree sorry i know i'm breaking the rules i don't condone this as normal behavior, just trying to get it fixed ASAP

non-production testing branch sounds like a better idea every day

**Comment by binary1230** [comment]
also, this is the wrong file anyway i need prereg_closed.html, will fix.

**Comment by kitsuta** [comment]
I think for event-specific plugins like this, it's totally fine for people who control that event to pretty much do as they like. :)

In terms of the main repo, that would be something like merging directly into an event's branch. Like if AC needed me to do something in the main repo and they needed it yesterday, I could shove that into `ac-staging` immediately and then have it code-reviewed for master.

**Pull request merged**
