### PR TITLE
override band plugin blocks with magstock-specific info

### PR DESCRIPTION
**Pull request by binary1230**
Allow magstock to override sections of agreement without needing to paste the entire agreement.html here.

now includes @cybersenshi's updated text (but not [correct] CSS re-styling) from her WIP PR: https://github.com/magfest/magstock/pull/64

requires the following to be merged first:
- https://github.com/magfest/bands/pull/27

### CODE REVIEW

**Comment by EliAndrewC** [comment]
I'll need to see how this works out in practice.  I like the idea, but at a glance, it doesn't look like this will necessarily reduce the amount of copy/paste and/or overriding that we have to do.

**Comment by kitsuta** [comment]
I like this. One thing it will get us is the ability to separate/protect the form part of the page, allowing child templates to just override the text parts without having to worry about bugfixes/additions/etc to the form. Many of our templates unfortunately don't benefit from that, being JUST a form, but it's good here.

**Comment by binary1230** [comment]
hey @EliAndrewC @kitsuta @cybersenshi go ahead and review this, it's ready.  I think it ended up being a big win.

As you can see, the magstock block overrides are just about zero HTML elements, zero styling, and are very simple to achieve the desired result.  Check out this file to see that it's a lot simpler than the previous approach: https://raw.githubusercontent.com/magfest/magstock/6c685b15675cf4ad300e8f34e601399532d59b4c/magstock/templates/bands/agreement.html

This is also a big win in that the styling work which @cybersenshi is doing now only has to take place in the bands plugin, not in magstock, so we don't have to worry about mirroring two copies of the same styling in bands plugin and in magstock plugin, and we will automatically get those style changes when we bring this into maglabs and prime.

**Comment by kitsuta** [comment]
Uh... where's agreement-base.html? :)

**Comment by kitsuta** [comment]
Nevermind, found it. For some reason I didn't get the email about the bands PR.

**Comment by cybersenshi** [comment]
+1 Correct text.

**Comment by EliAndrewC** [comment]
+1 (belatedly)

I agree that this did make the event-specific code a lot cleaner with less copy/paste than we'd have had otherwise.

**Pull request merged**
